### ISSUE TITLE
phpstan.excludeFiles option does not exclude files

### ISSUE THREAD

**Issue by jca** [calvinbaart/vscode-phpstan#5]
Files/folders added either to "files.exclude" and "phpstan.excludeFiles" should be excluded from phpstan checks as well, but it is not the case for me. The folders are already excluded in "files.exclude" successfully, but errors pop-up from the extension, even when the phpstan.excludeFiles option is set.

```
// Example workspace settings
{
	"folders": [
		{
			"path": "/Users/admin/Workspaces/myproject"
		}
	],
	"settings": {
		"phpstan.excludeFiles": [
			"mixedvendor",
			"mixedvendor/",
			"mixedvendor/*",
			"/mixedvendor",
			"/mixedvendor/",
			"/mixedvendor/*",
			"**/mixedvendor",
			"**/mixedvendor/",
			"**/mixedvendor/*",
		],
	},
}
```

This is happens MAC OSX

**Comment by calvinbaart** [comment]
Should be fixed in v0.1.8

**Comment by jca** [comment]
Thanks Calvin for looking into it, but the bug is still present for me in v0.1.8
VS Code version v1.24.11
Running on Mac OS High Sierra

**Comment by calvinbaart** [comment]
Reopened, I'll look into this. Does the excludeFiles option not work when opening the ignored file or when scanning the whole directory (PHPStan Scan of Errors command)?

**Comment by jca** [comment]
Sorry, this morning I can't execute phpstan on my host system (Mac OSX) and I don't have the time to fix this unrelated issue.
When phpstan worked, the error showed directly in the "problems" bottom tab. The parent folder in the filesystem tab was shown in red.

**Comment by binarious** [comment]
Any news? Still having this issue with the latest version.

```
"phpstan.excludeFiles": ["*Test.php"]
```
Problems are shown when the file is being saved.
